### ISSUE TITLE
selenium is not starting its server

### ISSUE THREAD

**Issue by azerafati** [sylvaindumont/docker-node-karma-protractor-chrome#10]
I know this is not the place to ask about this, but I'm getting this error when starting the webdriver
```
$ webdriver-manager start
[14:49:27] I/start - java -Djava.security.egd=file:///dev/./urandom -Dwebdriver.chrome.driver=/usr/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.35 -Dwebdriver.gecko.driver=/usr/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.19.1 -jar /usr/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.8.1.jar -port 4444
[14:49:27] I/start - seleniumProcess.pid: 164
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/openqa/grid/selenium/GridLauncherV3 : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
[14:49:27] I/start - Selenium Standalone has exited with code 1
```

My question is if I can use this docker image just to run the protractor without karma ?  according to this [Stackoverflow](https://stackoverflow.com/q/11532625/3160597), the problem is about mismatched versions of Java and Selenium but this image is using openJDK 8 jre; so there shouldn't be a problem with that right?
I'm using gitlab runner for this test and using the following commands in `.gitlab-ci.yml`
```
  script:
     - apt-get update
     - apt-get install -y openjdk-8-jdk
     - npm install -g protractor
     - webdriver-manager update
     - webdriver-manager start
     - protractor protractor.conf.js


```

**Comment by sylvaindumont** [comment]
Which tag do you use?
`latest` tag corresponds to `xvfb` branch
`master` branch is on `headless` tag
On the xvfb branch openjdk-7 is still installed, I will upgrade to openjdk-8 if openjdk-7 causes errors

`xvfb` branch was useful before chrome added headless mode, but now `headless` branch is much better (more recent chromium version, lighter...), the `latest` tag is still xvfb only to avoid breaking builds.

`alpine` branch is even lighter, if you don't cache your node_modules, it's the best.
The only change to make to your protractor config to use `headless` or `alpine` tag is the chrome `args` (you must set it to `'args': ['no-sandbox', 'headless', 'disable-gpu']`

`headless` `alpine` don't use `root` user so you will need to remove the `apt-get` commands from your script.

And yes, you can run protractor without karma :)

**Comment by azerafati** [comment]
I guess I'm not getting the hang of it, Maybe I've got it the wrong way. I'm still getting the same error even after your commit. 
Am I doing it the correct way?
* I'm installing the protractor and then start the webdriver-manager, Is that supposed to be so? Can't we have it pre-installed in the docker image?
* Selenium depends on java 6, so wee should have never got this error in the first place. Any Idea?
* Is there a working example you can provide on gitlab in the README? that's pretty necessary I think. Going to make a PR as soon as I get this going myself.

**Comment by sylvaindumont** [comment]
xvfb build failed because openjdk-8-jre-headless wasn't available on jessie, I upgraded to stretch to fix it.

preinstalling chromedriver could help too, it's already done in the alpine image because webdriver-manager download libc binarries instead of musl binaries. It could be installed on debian images too, so we could use it when webdriver downloaded binaries mismatch.

**Comment by sylvaindumont** [comment]
Seems like it's resolved, feel free to reopen if not.
