### ISSUE TITLE
The headless tag does not work anymore due to an update of ChromeDriver

### ISSUE THREAD

**Issue by ngeor** [sylvaindumont/docker-node-karma-protractor-chrome#19]
Since a couple of days ago, we can't run protractor tests with the `weboaks/node-karma-protractor-chrome:headless` image. The reason has to do with a new version of chromedriver (2.43). Protractor tries to automatically download the most recent chromedriver version. Based on our logs everything was working fine until version 2.42. A few days ago, 2.43 was released and we get this error:

```
[11:05:30] I/downloader - curl -o/code/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.43.zip https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
[11:05:31] I/update - chromedriver: unzipping chromedriver_2.43.zip
[11:05:32] I/update - chromedriver: setting permissions to 0755 for /code/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.43
(node:1398) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[11:05:40] I/launcher - Running 1 instances of WebDriver
[11:05:40] I/direct - Using ChromeDriver directly...
[11:06:40] E/runner - Unable to start a WebDriver session.
[11:06:40] E/launcher - Error: SessionNotCreatedError: session not created: Chrome version must be >= 69.0.3497.0
  (Driver info: chromedriver=2.43.600233 (523efee95e3d68b8719b3a1c83051aa63aa6b10d),platform=Linux 4.9.93-boot2docker x86_64)
    at Object.checkLegacyResponse (/code/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/code/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/code/node_modules/selenium-webdriver/lib/http.js:440:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[11:06:40] E/launcher - Process exited with error code 100
An unexpected error occurred: undefined
```

I noticed that you have fresh images but none of them is using node 8.

Do you plan to update the `headless` tag or maybe create a `debian-node8` tag? That would be great for us :)

**Comment by sylvaindumont** [comment]
@ngeor  The current debian images come with chromium 68.0.3440.75, which is no longer supported with chromedriver 2.43, I just rebuilt the debian images (`headless`, `debian-node6`, `debian-node8`, `debian-node10`), they now include the latest chromium from stretch (69.0.3497.92 )

**Comment by ngeor** [comment]
wow, thank you very much @sylvaindumont for such a fast solution!!!

I am running the tests now and they are all passing fine.

Meanwhile, I was thinking maybe the chrome version could be included in the Docker image tag. So instead of `debian-node8` you could also have `debian-node8-chrome-68`. I can imagine this is not easy to do because you don't know in advance what chrome version `apt-get` is going to fetch... but just an idea.

Thank you again!
