### ISSUE TITLE
Chrome version mismatch

### ISSUE THREAD

**Issue by michael-leonard-slalom** [sylvaindumont/docker-node-karma-protractor-chrome#26]
Selenium webdriver fails to launch with this image due to a Chrome version mismatch.  Any suggestions?

```
[17:48:16] E/launcher - session not created: This version of ChromeDriver only supports Chrome version 79
  (Driver info: chromedriver=79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614}),platform=Linux 4.19.78-coreos x86_64)
[17:48:16] E/launcher - SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 79
  (Driver info: chromedriver=79.0.3945.36 (3582db32b33893869b8c1339e8f4d9ed1816f143-refs/branch-heads/3945@{#614}),platform=Linux 4.19.78-coreos x86_64)
    at Object.checkLegacyResponse (/opt/atlassian/pipelines/agent/build/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/opt/atlassian/pipelines/agent/build/node_modules/selenium-webdriver/lib/http.js:509:13)
    at /opt/atlassian/pipelines/agent/build/node_modules/selenium-webdriver/lib/http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
From: Task: WebDriver.createSession()
    at Function.createSession (/opt/atlassian/pipelines/agent/build/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/opt/atlassian/pipelines/agent/build/node_modules/selenium-webdriver/chrome.js:761:15)
    at Direct.getNewDriver (/opt/atlassian/pipelines/agent/build/node_modules/protractor/built/driverProviders/direct.js:77:33)
    at Runner.createBrowser (/opt/atlassian/pipelines/agent/build/node_modules/protractor/built/runner.js:195:43)
    at /opt/atlassian/pipelines/agent/build/node_modules/protractor/built/runner.js:339:29
    at _fulfilled (/opt/atlassian/pipelines/agent/build/node_modules/q/q.js:834:54)
    at /opt/atlassian/pipelines/agent/build/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/opt/atlassian/pipelines/agent/build/node_modules/q/q.js:796:13)
    at /opt/atlassian/pipelines/agent/build/node_modules/q/q.js:556:49
    at runSingle (/opt/atlassian/pipelines/agent/build/node_modules/q/q.js:137:13)
```

**Comment by sylvaindumont** [comment]
Chromium 79 isn't available yet in debian, but you can use a webdriver version compatible with the current chromium version in debian (`78.0.3904.108`) as [explained here](https://github.com/sylvaindumont/docker-node-karma-protractor-chrome/issues/22#issuecomment-545059191).  
You can also use the alpine version of the image, with chromium 79. To use the alpine version, you have to use the webdriver binary bundled in the image with `chromeDriver: '/usr/bin/chromedriver'`.

**Comment by michael-leonard-slalom** [comment]
Thanks!  I chose the alpine version in order to work with latest Chrome.
