### ISSUE TITLE
Chromium version seems to be incompatible with chromedriver

### ISSUE THREAD

**Issue by DerH4NNES** [sylvaindumont/docker-node-karma-protractor-chrome#27]
I'm using the latest container in a bitbucket pipelines configuration.

**+ ng e2e --protractor-config=e2e/protractor.pipeline.conf.js
Your global Angular CLI version (9.0.5) is greater than your local
version (9.0.4). The local Angular CLI version is used.
To disable this warning use "ng config -g cli.warnings.versionMismatch false".
[09:46:09] I/file_manager - creating folder /opt/atlassian/pipelines/agent/build/node_modules/protractor/node_modules/webdriver-manager/selenium
[09:46:09] I/config_source - curl -o/opt/atlassian/pipelines/agent/build/node_modules/protractor/node_modules/webdriver-manager/selenium/chrome-response.xml https://chromedriver.storage.googleapis.com/
[09:46:09] I/downloader - curl -o/opt/atlassian/pipelines/agent/build/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_80.0.3987.106.zip https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_linux64.zip
[09:46:09] I/update - chromedriver: unzipping chromedriver_80.0.3987.106.zip
[09:46:09] I/update - chromedriver: setting permissions to 0755 for /opt/atlassian/pipelines/agent/build/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_80.0.3987.106
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/elements : es2015 as esm2015
chunk {main} main.js, main.js.map (main) 9.9 MB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 162 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 177 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 219 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.8 MB [initial] [rendered]
Date: 2020-03-06T09:46:52.915Z - Hash: 39c984b642ba795fdca4 - Time: 39537ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.
[09:46:53] I/launcher - Running 1 instances of WebDriver
[09:46:53] I/direct - Using ChromeDriver directly...
[09:46:53] E/launcher - session not created: This version of ChromeDriver only supports Chrome version 80
  (Driver info: chromedriver=80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185}),platform=Linux 4.19.78-coreos x86_64)
[09:46:53] E/launcher - SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 80
  (Driver info: chromedriver=80.0.3987.16 (320f6526c1632ad4f205ebce69b99a062ed78647-refs/branch-heads/3987@{#185}),platform=Linux 4.19.78-coreos x86_64)
    at Object.checkLegacyResponse (/opt/atlassian/pipelines/agent/build/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/opt/atlassian/pipelines/agent/build/node_modules/selenium-webdriver/lib/http.js:509:13)
    at /opt/atlassian/pipelines/agent/build/node_modules/selenium-webdriver/lib/http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
From: Task: WebDriver.createSession()
    at Function.createSession (/opt/atlassian/pipelines/agent/build/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/opt/atlassian/pipelines/agent/build/node_modules/selenium-webdriver/chrome.js:761:15)
    at Direct.getNewDriver (/opt/atlassian/pipelines/agent/build/node_modules/protractor/built/driverProviders/direct.js:77:33)
    at Runner.createBrowser (/opt/atlassian/pipelines/agent/build/node_modules/protractor/built/runner.js:195:43)
    at /opt/atlassian/pipelines/agent/build/node_modules/protractor/built/runner.js:339:29
    at _fulfilled (/opt/atlassian/pipelines/agent/build/node_modules/q/q.js:834:54)
    at /opt/atlassian/pipelines/agent/build/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/opt/atlassian/pipelines/agent/build/node_modules/q/q.js:796:13)
    at /opt/atlassian/pipelines/agent/build/node_modules/q/q.js:556:49
    at runSingle (/opt/atlassian/pipelines/agent/build/node_modules/q/q.js:137:13)
[09:46:53] E/launcher - Process exited with error code 199**

**Comment by sylvaindumont** [comment]
Unfortunately, it cannot be upgraded yet because 79 is the last version available in debian (https://packages.debian.org/buster/chromium) and alpine (https://pkgs.alpinelinux.org/packages?name=chromium&branch=edge).
The fix until newer chromium versions are released in debian and alpine is to [pin the chromedriver version](https://github.com/sylvaindumont/docker-node-karma-protractor-chrome/issues/22#issuecomment-545059191)

**Comment by sylvaindumont** [comment]
all images have been updated to `80.0.3987.132`
